In [2]:
# 파이토치에서는 텐서를 사용하여 모델의 입력, 출력, 모델의 배개변수를 부호화함
import torch
import numpy as np

In [3]:
### 텐서 초기화
# 데이터로부터 직접 생성하기
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

# 넘파이 배열로부터 생성하기
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

# 다른 텐서로부터 생성하기
x_ones = torch.ones_like(x_data)   # x_data의 속성을 유지함
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float)  # x_data의 속성을 덮어씀
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7991, 0.1515],
        [0.4088, 0.2868]]) 



In [6]:
# 무작위 또는 상수 값을 사용하기 
# shpae는 텐서의 차원을 나타내는 튜플

shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zero_tensor = torch.zeros(shape)

print(rand_tensor, "\n", ones_tensor, "\n", zero_tensor)

tensor([[0.6000, 0.7092, 0.4984],
        [0.3893, 0.6339, 0.2087]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
### 텐서의 속성
tensor = torch.rand(3,4)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


In [8]:
### 텐서 연산
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

# 넘파이식의 표준 인덱싱과 슬라이싱
tensor = torch.ones(4,4)
print('first row: ', tensor[0])
print('first column: ', tensor[:,0])
print('last column: ', tensor[...,-1])
tensor[:,1]=0
print(tensor)

first row:  tensor([1., 1., 1., 1.])
first column:  tensor([1., 1., 1., 1.])
last column:  tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [9]:
### 텐서 합치기
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [11]:
### 산술 연산
# 두 텐서 간의 행렬 곱 matrix multiplication, 123은 모두 같은 값을 가짐
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)

# 요소별 곱 element-wise product, 123은 모두 같은 값을 가짐
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(y1)
print(z1)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
